name: tala_quran_app
description: "Tala Quran: A premium, realistic 3D Quran experience with AI Tajweed analysis, recitation recognition, and smart notifications."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.2
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  sqflite: ^2.3.0
  path: ^1.8.3
  dio: ^5.4.1
  archive: ^3.4.10
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  flutter_timezone: ^3.0.1
  share_plus: ^10.1.4
  record: ^5.2.0
  permission_handler: ^11.3.1
  vector_math: ^2.1.4
  wakelock_plus: ^1.5.1
  app_settings: ^7.0.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
dependency_overrides:
  record_linux: ^1.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/surahs/
    - assets/images/
    - assets/data/
    - assets/mushaf/
    - assets/mushaf/data/
